name: Feature request
description: Suggest an improvement or new capability.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the project.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What limitation or pain point are you facing?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your proposed change and why it helps.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Optional alternatives or workarounds you tried.
    validations:
      required: false
